In [2]:
import numpy as np


In [3]:
np.empty(0,2)

TypeError: Cannot interpret '2' as a data type

In [15]:
a=np.array([[1,2,3,4],[1,3,4,5],[2,3,4,5],[3,4,5,6]])
print(a,'\n',a.shape)


[[1 2 3 4]
 [1 3 4 5]
 [2 3 4 5]
 [3 4 5 6]] 
 (4, 4)


In [31]:
b=a[np.where(a[:,0]==1)][:,1:3]
print(b)
print(np.maximum(0,b[0,1]))

[[2 3]
 [3 4]]
3


In [35]:
np.argwhere(a[:,0]==2).item()

2

In [1]:
import random

In [6]:
print(random.random())

0.8799213017951055


In [7]:
import torch

In [10]:
a=torch.tensor((1,2))
a

tensor([1, 2])

In [17]:
b=a.repeat(2,5,4)
print(b.shape)

torch.Size([2, 5, 8])


In [20]:
a[0]

tensor(1)

In [21]:
import numpy as np

In [24]:
s=np.eye(2)[1-1].astype(int)
s.shape

(2,)

In [26]:
s[0]

1

In [27]:
import torch

In [28]:
a=torch.tensor(2)

In [29]:
b=a.repeat(1,1,1)
b

tensor([[[2]]])

In [31]:
a=torch.tensor([1.,2.,])
b=torch.tensor([2.,3.])
criterion=torch.nn.MSELoss()
loss=criterion(a,b)
loss

tensor(1.)

In [35]:
a=torch.ones(5,3,4)
a.shape[1]

3