In [2]:
import numpy as np


In [3]:
np.empty(0,2)

TypeError: Cannot interpret '2' as a data type

In [15]:
a=np.array([[1,2,3,4],[1,3,4,5],[2,3,4,5],[3,4,5,6]])
print(a,'\n',a.shape)


[[1 2 3 4]
 [1 3 4 5]
 [2 3 4 5]
 [3 4 5 6]] 
 (4, 4)


In [31]:
b=a[np.where(a[:,0]==1)][:,1:3]
print(b)
print(np.maximum(0,b[0,1]))

[[2 3]
 [3 4]]
3


In [35]:
np.argwhere(a[:,0]==2).item()

2